import "./globals.css";

import type { Metadata } from "next";
import { Fira_Code, Montserrat } from "next/font/google";
import localFont from "next/font/local";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

const pixoReto = localFont({
  src: "../public/PixoReto.ttf",
  variable: "--font-pixo-reto",
});

export const metadata: Metadata = {
  title: "Arila Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${firaCode.variable} ${pixoReto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
